name: health_studio_user
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.0.31+67

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # The following package is added to implement State Management
  get: ^4.6.5
  flutter_screenutil: ^5.6.0
  # The following package allows you to view the app in different device types
  device_preview: ^1.1.0
  # The following package is to use carousel slider feature
  carousel_slider: ^4.1.1
  # The following package is to use SVG images
  flutter_svg: ^1.1.6
  # The following package is integrated to make network calls
  dio: ^4.0.6
  # The following package is used for launching a URL
  url_launcher: ^6.1.7
  # The following package is used for getting the app version
  package_info_plus: ^3.0.2
  # The following package is for sticky headers
  flutter_sticky_header: ^0.6.5
  sticky_headers: ^0.3.0+2
  # The following package is added to play Intro Video
  video_player: ^2.5.1
  # The following package is added to implement Google Sign In
  google_sign_in: ^5.4.3
  # The following package is added to implement Share
  share_plus: ^6.3.0
  # The following package is added to implement In App Webview for Payment
  flutter_inappwebview: ^5.7.2+3
  # The following package is added to get device info
  device_info_plus: ^8.0.0
  # The following package is added to implement FCM
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  # The following package is added to integrate Crashlytics
  firebase_crashlytics: ^3.1.1
  # The following package is added to implement to APNs
  # flutter_apns: ^1.6.0
  flutter_facebook_auth: ^5.0.7
  # The following package is added to implement sign in with apple
  sign_in_with_apple: ^4.3.0
  # The following package is added to compare version number
  version: ^3.0.2
  smooth_page_indicator: ^1.0.1
  # The following package is used to generate pie charts
  syncfusion_flutter_charts: ^20.4.48
  
# dependency_overrides:
#   firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
  # The following package is integrated to add App Logo
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_white_bg.jpg"
  

flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/menu/
  - assets/videos/intro_video.mp4

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        
        
        
        
  
