name: health_studio_user
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

  # The following package is added to implement State Management
  get: ^4.6.5


  # The following package allows you to view the app in different device types
  device_preview: 1.0.0

  # The following package is integrated to display SVG Images
  flutter_screenutil: ^5.5.3+2

  # The following package is to use carousel slider feature
  carousel_slider: ^4.1.1

  # The following package is to use SVG images
  flutter_svg: ^1.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  
  assets:
    
    - assets/images/health_studio_logo.png
    - assets/images/settings_icon.png
    - assets/images/feature1.png
    - assets/images/feature2.png
    - assets/images/food1.png
    - assets/images/food2.png
    - assets/images/background.png
    
 
    


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        
        
        
        
  
