name: health_studio_user
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.0.0+5

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # The following package is added to implement State Management
  get: ^4.6.5
  flutter_screenutil: ^5.6.0
  # The following package allows you to view the app in different device types
  device_preview: ^1.1.0
  # The following package is to use carousel slider feature
  carousel_slider: ^4.1.1
  # The following package is to use SVG images
  flutter_svg: ^1.1.6
  # The following package is integrated to make network calls
  dio: ^4.0.6
  # The following package is integrated to cache the network images for faster loading
  cached_network_image: ^3.2.3
  # The following package is for sticky headers
  flutter_sticky_header: ^0.6.5
  sticky_headers: ^0.3.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
  # The following package is integrated to add App Logo
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_white_bg.jpg"
  

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/menu/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        
        
        
        
  
